import { projects } from "@/data/projects";
import { profile } from "@/lib/site";

export function About() {
  return (
    <section className="section about" id="about" data-nav="" aria-labelledby="about-title">
<div className="wrap">
<div className="about-grid"><div className="reveal"><p className="section-kicker mono"><span className="index">02 /</span> THE PERSON BEHIND THE CODE</p><h2 id="about-title">More than an interface.</h2><p className="about-statement">I care about what you see.<br /><span>And everything that makes it work.</span></p><p className="about-text">I’m Muhammad Arsalan, a full stack developer in Islamabad. My work spans learning platforms, video tools, inventory systems, and document wallets. I turn complex requirements into clear interfaces and maintainable application code.</p><p className="about-text">I’m currently a Senior Software Engineer at Idanimo LLC. Previously, I worked as a Full Stack Developer at Aurora Solutions. Since August 2022, I’ve worked across frontend development, backend integration, and React Native applications.</p><a className="about-link" href="/resume/Muhammad-Arsalan-Resume.pdf" download="Muhammad-Arsalan-Resume.pdf">The full story, in my resume <svg className="icon" aria-hidden="true"><use href="#i-download" /></svg></a><p className="about-profile-link"><a href={profile.linkedin} target="_blank" rel="noopener noreferrer">More about my background on LinkedIn <span aria-hidden="true">↗</span><span className="sr-only"> (opens in a new tab)</span></a></p></div>
<div className="reveal"><div className="approach-list"><div className="approach-item"><span className="approach-number mono">01</span><div><h3>Custom websites.</h3><p>Responsive React and Next.js websites, dashboards, and admin interfaces built around the people using them.</p></div></div><div className="approach-item"><span className="approach-number mono">02</span><div><h3>Full-stack applications.</h3><p>Node.js and NestJS backends, API integrations, authentication, and connected account workflows.</p></div></div><div className="approach-item"><span className="approach-number mono">03</span><div><h3>Mobile & ongoing support.</h3><p>React Native applications, maintenance, and performance improvements, with AWS and Docker deployment support.</p></div></div></div><div className="profile-metrics"><div className="metric"><strong>02</strong><span>ENGINEERING ROLES</span></div><div className="metric"><strong>{String(projects.length).padStart(2, "0")}</strong><span>SELECTED PROJECTS</span></div><div className="metric"><strong>03</strong><span>CERTIFICATIONS</span></div></div></div></div>
</div>
</section>
  );
}
