export function About() {
  return (
    <section className="section about" id="about" data-nav="" aria-labelledby="about-title">
<div className="wrap">
<div className="about-grid"><div className="reveal"><p className="section-kicker mono"><span className="index">02 /</span> THE PERSON BEHIND THE CODE</p><h2 id="about-title">More than an interface.</h2><p className="about-statement">I care about what you see.<br /><span>And everything that makes it work.</span></p><p className="about-text">I’m Muhammad Arsalan, a full-stack developer based in Islamabad. My work connects carefully built interfaces with the systems behind them: web applications, native mobile experiences, cloud infrastructure, and AI.</p><p className="about-text">At Idanimo LLC, I work as a Senior Software Engineer. Before that, I built web and mobile products at Aurora Solutions. Across both roles, the focus has been the same: thoughtful implementation, secure foundations, and maintainable software.</p><a className="about-link" href="/resume/Muhammad-Arsalan-Resume.pdf" download="Muhammad-Arsalan-Resume.pdf">The full story, in my resume <svg className="icon" aria-hidden="true"><use href="#i-download" /></svg></a></div>
<div className="reveal"><div className="approach-list"><div className="approach-item"><span className="approach-number mono">01</span><div><h3>Interfaces with intention.</h3><p>Pixel-perfect web and mobile experiences built with React, Next.js, and React Native.</p></div></div><div className="approach-item"><span className="approach-number mono">02</span><div><h3>Depth beyond the front end.</h3><p>NestJS, APIs, AWS, and Docker connect the experience to dependable application foundations.</p></div></div><div className="approach-item"><span className="approach-number mono">03</span><div><h3>Curiosity, put to work.</h3><p>From voice-enabled AI to blockchain integrations and digital wallets, I enjoy bringing new capabilities into useful products.</p></div></div></div><div className="profile-metrics"><div className="metric"><strong>02</strong><span>ENGINEERING ROLES</span></div><div className="metric"><strong>06</strong><span>FEATURED PRODUCTS</span></div><div className="metric"><strong>03</strong><span>CERTIFICATIONS</span></div></div></div></div>
</div>
</section>
  );
}
