export function Experience() {
  return (
    <section className="section experience" id="experience" data-nav="" aria-labelledby="experience-title"><div className="wrap">
<div className="section-heading reveal"><div><p className="section-kicker mono"><span className="index">03 /</span> EXPERIENCE &amp; FOUNDATIONS</p><h2 id="experience-title">The journey so far.</h2></div><p className="section-subtitle">Hands-on engineering, across teams,<br />products, and platforms.</p></div>
<div className="experience-list">
<article className="experience-item reveal"><div className="experience-date mono"><span>AUG 2024 — PRESENT</span><br /><span className="current"><span className="dot" /> CURRENT ROLE</span></div><div className="experience-main"><h3>Senior Software Engineer</h3><div className="experience-company">Idanimo LLC <span className="location">/ Islamabad, Pakistan</span></div><ul className="experience-points"><li>Lead development of CVVID, a video CV platform with recording, editing, and QR-code sharing.</li><li>Developed a flexible Online Visa Application System with Next.js, React Flow, and PDF integration.</li><li>Built the DDID React Native wallet for digitally signed documents and modernized its React dependencies.</li><li>Revamped the Idnmo website using Next.js, Tailwind CSS, Server Actions, and SEO optimizations.</li><li>Integrated Docker, NextAuth, and Redux Toolkit, with GitFlow and secure-storage practices.</li></ul></div></article>
<article className="experience-item reveal"><div className="experience-date mono">AUG 2022 — JUL 2024</div><div className="experience-main"><h3>Full Stack Developer</h3><div className="experience-company">Aurora Solutions <span className="location">/ Islamabad, Pakistan</span></div><ul className="experience-points"><li>Built an educational platform with NestJS, AWS EC2, and S3 for scalable video hosting and course content.</li><li>Created pixel-perfect web and mobile applications for store and inventory management.</li><li>Integrated blockchain functionality across Fitcoin’s React web and React Native mobile applications.</li><li>Applied GitFlow, Docker, and secure-storage practices to support performance, security, and maintainability.</li></ul><div className="award"><svg className="icon" aria-hidden="true"><use href="#i-award" /></svg>Employee of the Month · September 2023</div></div></article>
</div>
<div className="credentials"><article className="credential-box reveal"><div className="credential-label mono"><svg className="icon" aria-hidden="true"><use href="#i-graduation" /></svg> EDUCATION</div><h3 className="education-title">Bachelor’s in Computer Science</h3><p className="education-name">FAST — National University of Computer and Emerging Sciences</p><span className="education-date mono">2018 — 2022 · ISLAMABAD</span></article><article className="credential-box reveal"><div className="credential-label mono"><svg className="icon" aria-hidden="true"><use href="#i-certificate" /></svg> CERTIFICATIONS</div><a className="cert-link" href="https://www.hackerrank.com/certificates/iframe/576535bc58ff" target="_blank" rel="noopener noreferrer"><div>Frontend Developer (React)<span>HackerRank</span></div><svg className="icon" aria-hidden="true"><use href="#i-arrow-up-right" /></svg><span className="sr-only">Opens in a new tab</span></a><a className="cert-link" href="https://www.hackerrank.com/certificates/iframe/ce2ae35fa7ec" target="_blank" rel="noopener noreferrer"><div>React (Basic)<span>HackerRank</span></div><svg className="icon" aria-hidden="true"><use href="#i-arrow-up-right" /></svg><span className="sr-only">Opens in a new tab</span></a><a className="cert-link" href="https://www.hackerrank.com/certificates/iframe/0c50b831728d" target="_blank" rel="noopener noreferrer"><div>CSS<span>HackerRank</span></div><svg className="icon" aria-hidden="true"><use href="#i-arrow-up-right" /></svg><span className="sr-only">Opens in a new tab</span></a></article></div>
</div></section>
  );
}
